apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: budget-app
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'flask-app'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - budget-app
        relabel_configs:
          # Only scrape pods with app=flask-app label
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: flask-app
            action: keep
          # Set the metrics path
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          # Use pod IP and port 5000
          - source_labels: [__address__]
            action: replace
            regex: ([^:]+)(?::\d+)?
            replacement: $1:5000
            target_label: __address__
          # Add pod name as label
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          # Add namespace as label
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace

      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090'] 