version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 main:app
    volumes:
      - ./app:/app
    expose:
      - 5000
    env_file:
      - .env

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - web

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data: