apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: budget-app
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP 