apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: budget-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  # Source repository
  source:
    repoURL: https://github.com/ChenBracha/devops-final-project.git
    targetRevision: HEAD
    path: k8s
    directory:
      recurse: true  # Recursively scan subdirectories
  
  # Destination cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: budget-app
  
  # Sync policy
  syncPolicy:
    automated:
      prune: true       # Delete resources that are removed from Git
      selfHeal: true    # Sync when cluster state differs from Git
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true  # Auto-create namespace if it doesn't exist
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Ignore differences (optional)
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Don't sync replica count if manually scaled

