# .github/workflows/ci.yml

name: CI Pipeline with Security Scans

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Job 1: Lint code and scan dependencies
  test-and-scan-repo:
    name: Lint and Scan Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      # --- NEW STEP: Scan for vulnerabilities in dependencies ---
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'

  # Job 2: Build the Docker image and scan it for vulnerabilities
  build-and-scan-image:
    name: Build and Scan Docker Image
    runs-on: ubuntu-latest
    needs: test-and-scan-repo # This job runs only after the first one succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # This step builds the image and loads it into the local Docker daemon
      # of the GitHub runner, but does NOT push it to a registry.
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: my-grocery-app:latest
          push: false 

      # --- NEW STEP: Scan the newly built Docker image ---
      - name: Run Trivy vulnerability scanner on Docker image
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'my-grocery-app:latest'
          ignore-unfixed: true
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'